### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xhzengAIB** [pj4533/AVCaptureMultipeerVideoDataOutput#1]
@pj4533 

Hi！
     I will be crash，
log：
2014-01-07 23:24:26.254 MultipeerVideoOutputSample[2133:3e0f] PEER CONNECTED: iPad Simulator
2014-01-07 23:24:33.917 MultipeerVideoOutputSample[2133:60b] Received memory warning.
2014-01-07 23:24:36.547 MultipeerVideoOutputSample[2133:60b] Received memory warning.

how i can fix it？

Jack

**Comment by pj4533** [comment]
Your best bet is to lower the frame rate here:

https://github.com/pj4533/AVCaptureMultipeerVideoDataOutput/blob/master/Sample/MultipeerVideoOutputSample/SGSViewController.m#L47

Still working out how to make this reliable.    But start low (2 fps), and just bump it up by hand.

**Comment by xhzengAIB** [comment]
@pj4533 
ok! thanks you, I'll give it a try

**Comment by xhzengAIB** [comment]
@pj4533 
This video is not good, there are other solutions?

**Comment by pj4533** [comment]
Well, you could fix the memory issues with higher frame rates!     Likely some sort of frame buffer sharing is required.   Also depends on your device.  I can handle 15fps and more on my iPhone5S.

**Comment by xhzengAIB** [comment]
I have no idea to fix it, I hope you can give me help and guidance

**Comment by pj4533** [comment]
Added a well described issue:    https://github.com/pj4533/AVCaptureMultipeerVideoDataOutput/issues/2

**Comment by Serlight** [comment]
@xhzengAIB   how to appeare the sent data on screen?
